### ISSUE TITLE
Example of using onX in a CSP environment where addEventListener is used.

### ISSUE THREAD

**Issue by rouilj** [Tram-One/tram-lite#29]
## Summary

When using a content security policy, ```onX``` (```onclick```, ```onchange``` etc.) attributes are discouraged
as they can not be protected by a nonce indicating that the javascript code is secure/authorized. (You
can use a sha256 checksum but keeping this up to date can be become a major chore.)

I did this using addEventListener with the following:
```
<!DOCTYPE HTML>
<html>
  <head>
    <script src="https://unpkg.com/tram-lite@3"></script>
  </head>
  <body>
    <template is="component-definition">
      <my-button label="click me" count="0">
        <button>
          ${'label'}: ${'count'}
        </button>
        <script>
          this.shadowRoot.querySelector('button').focus()
          this.shadowRoot.querySelector('button').addEventListener(
              "click", (event) => increment(event))
        </script>
      </my-button>
    </template>

    <my-button label="My Button"></my-button>

    <my-button></my-button>

    <script>
      function increment(event) {
        const myButton = event.target.getRootNode().host;
        const currentCount = parseInt(myButton.getAttribute('count'));
        myButton.setAttribute('count', currentCount+1);
      }
    </script>
  </body>
</html>
```

While this works, it uses an anonymous function as the second argument to addEventListener. This
means that you can't easily remove the event listener.

It seems that:
```
          this.shadowRoot.querySelector('button').addEventListener("click", increment)
```
could work, but using this causes a traceback claiming that ```increment``` is undefined.
```
Uncaught ReferenceError: increment is not defined
    at CustomTramLiteElement.eval (eval at scopedEval (tram-lite@3:128:32), <anonymous>:5:46)
    at scopedEval (tram-lite@3:128:81)
    at tram-lite@3:142:29
    at NodeList.forEach (<anonymous>)
    at CustomTramLiteElement.connectedCallback (tram-lite@3:131:29)
```
This kind of makes sense as increment isn't defined until later in the file.

If the script that defines ```increment``` is moved before the ```my-button``` tag, it works as expected.
However this does mean that using a js script tag at the end of the body to define event handler's won't
work. 

Is there a way to defer running the embedded ```<script>``` in the template until after all js scripts
are parsed and loaded? I can use the anonymous function method with the noted drawback, but that's
not great.

I guess I could use:
```
document.querySelectorAll('my-button').forEach(
       (node) =>
           node.shadowRoot.querySelector('button').addEventListener('click', increment)
     )
```

inside a DOMContentLoaded handler in a top level script tag. But this means I have to add functionality
to the component from outside of the component declaration.

Within the component script tag, using:
```
           <script>
          this.shadowRoot.querySelector('button').focus()
          setTimeout(
              (node) => node.addEventListener("click",
                                              (event) => increment(event)
                                             ),
              2000,
              this.shadowRoot.querySelector('button')
          )
        </script>
      </my-button>
```
could work, but the 2000ms magic timing parameter is not a great solution.

Any ideas on how to:
* allow adding event handlers via addEventListener
* to elements of the shadow dom
* where the event handler is defined anywhere in the HTML file (including at the end of the body)
* and makes the event handler live as soon as possible after the dom is ready.

It seems some combination of document.addEventListener('DOMContentLoaded'), and a closure
should work. But I haven't found the right combination.

Thanks

-- rouilj

**Comment by JRJurman** [comment]
@rouilj Thanks for the information here, this is really detailed, and it is appreciated!

Having an elegant solution for `addEventListener` is definitely something we want to have an option for, so I'll do some experimentation here, and if there's a call for a new API, we can think around that too.

**Comment by rouilj** [comment]
Also there was some discussion of CSP and web components at:

  https://github.com/google/WebFundamentals/issues/8817

https://github.com/WICG/webcomponents/issues/627

sadly other than using a link tag for style it seems to have ended without a conclusion.

**Comment by JRJurman** [comment]
Okay, I'm going to try to think of more solutions here, but one potential solution is to **define the function in the script tag for the component mount**. This doesn't let you share or define the function elsewhere in the HTML document, but gives the option to attach and remove named functions.

<details>

  <summary>Snippet</summary>

```html
<script>
  function increment(event) {
    const myButton = event.target.getRootNode().host;
    const currentCount = parseInt(myButton.getAttribute('count'));
    myButton.setAttribute('count', currentCount+1);
  }
  
  const counterButton = this.shadowRoot.querySelector('button#counter');
  counterButton.addEventListener("click", increment);
</script>
```

</details>

<details>

  <summary>Full Code</summary>

```html
<script src="https://unpkg.com/tram-lite@3"></script>
<template is="component-definition">
  <my-button label="click me" count="0">
    <div>
      <button id="counter">
        ${'label'}: ${'count'}
      </button>
      <button id="clear">
        Clear Event
      </button>
    </div>
    <script>
      function increment(event) {
        const myButton = event.target.getRootNode().host;
        const currentCount = parseInt(myButton.getAttribute('count'));
        myButton.setAttribute('count', currentCount+1);
      }
      
      // can save increment to this.increment, if you want to be able to refer to this function outside of this script tag (not required though)
      this.increment = increment;
      
      
      const counterButton = this.shadowRoot.querySelector('button#counter');
      const clearButton = this.shadowRoot.querySelector('button#clear');
      
      counterButton.addEventListener("click", increment);
      clearButton.addEventListener("click", () => counterButton.removeEventListener('click', increment))
    </script>
  </my-button>
</template>

<my-button label="My Button"></my-button>

<my-button></my-button>
```

</details>
Codepen Link: <a href="https://codepen.io/JRJurman/pen/MWZpVza?editors=1000">https://codepen.io/JRJurman/pen/MWZpVza?editors=1000</a>

**Comment by JRJurman** [comment]
Another option is using `this.ownerDocument.addEventListener("DOMContentLoaded", ...)` inside the component mount script. This should allow you to place the script with the increment function anywhere in the document.

<details>

  <summary>Snippet</summary>

```html
<!-- in your component definition -->
<script>
  this.ownerDocument.addEventListener("DOMContentLoaded", (event) => {
    const counterButton = this.shadowRoot.querySelector('button#counter');
    counterButton.addEventListener("click", increment);
  });
</script>

<!-- end of document -->
<script>
  function increment(event) {
    const myButton = event.target.getRootNode().host;
    const currentCount = parseInt(myButton.getAttribute('count'));
    myButton.setAttribute('count', currentCount+1);
  }
</script>
```

</details>

<details>

  <summary>Full Code</summary>

```html
<script src="https://unpkg.com/tram-lite@3"></script>

<template is="component-definition">
  <my-button label="click me" count="0">
    <div>
      <button id="counter">
        ${'label'}: ${'count'}
      </button>
      <button id="clear">
        Clear Event
      </button>
    </div>
    <script>
      this.ownerDocument.addEventListener("DOMContentLoaded", (event) => {
        const counterButton = this.shadowRoot.querySelector('button#counter');
        const clearButton = this.shadowRoot.querySelector('button#clear');

        counterButton.addEventListener("click", increment);
        clearButton.addEventListener("click", () => counterButton.removeEventListener('click', increment))
      });
    </script>
  </my-button>
</template>

<my-button label="My Button"></my-button>
<my-button></my-button>

<script>
  function increment(event) {
    const myButton = event.target.getRootNode().host;
    const currentCount = parseInt(myButton.getAttribute('count'));
    myButton.setAttribute('count', currentCount+1);
  }
</script>
```

</details>

Codepen link: https://codepen.io/JRJurman/pen/rNoyroL?editors=1001

**Comment by JRJurman** [comment]
If you want to avoid reaching into the internals of a component (which I agree is probably not good), you could **set an attribute that will then trigger binding events**. You can do this with the Tram-Lite `addAttributeListener` function ([docs here](https://tram-one.io/tram-lite/#addAttributeListener)).

<details>

  <summary>Snippet</summary>

```html
<!-- in your component definition -->
<script>
  addAttributeListener(this, ['pending'], () => {
    const counterButton = this.shadowRoot.querySelector('button#counter');
    const clearButton = this.shadowRoot.querySelector('button#clear');

    counterButton.addEventListener("click", increment);
    clearButton.addEventListener("click", () => counterButton.removeEventListener('click', increment));
    this.removeAttribute('pending');
  });
</script>

<!-- elsewhere in your document -->
<script>
  function increment(event) {
    const myButton = event.target.getRootNode().host;
    const currentCount = parseInt(myButton.getAttribute('count'));
    myButton.setAttribute('count', currentCount+1);
  }
  
  document.querySelectorAll('my-button[pending=""]').forEach(newButton => {
    newButton.setAttribute('pending', 'ready')
  })
</script>
```

</details>

<details>

  <summary>Full Code</summary>

```html
<script src="https://unpkg.com/tram-lite@3"></script>

<template is="component-definition">
  <my-button label="click me" count="0" pending="">
    <div>
      <button id="counter">
        ${'label'}: ${'count'}
      </button>
      <button id="clear">
        Clear Event
      </button>
    </div>
    <script>
      addAttributeListener(this, ['pending'], () => {
        const counterButton = this.shadowRoot.querySelector('button#counter');
        const clearButton = this.shadowRoot.querySelector('button#clear');

        counterButton.addEventListener("click", increment);
        clearButton.addEventListener("click", () => counterButton.removeEventListener('click', increment));
        this.removeAttribute('pending');
      });
    </script>
  </my-button>
</template>

<my-button label="My Button"></my-button>
<my-button></my-button>

<script>
  function increment(event) {
    const myButton = event.target.getRootNode().host;
    const currentCount = parseInt(myButton.getAttribute('count'));
    myButton.setAttribute('count', currentCount+1);
  }
  
  document.querySelectorAll('my-button[pending=""]').forEach(newButton => {
    newButton.setAttribute('pending', 'ready')
  })
</script>
```

</details>

Codepend Link: https://codepen.io/JRJurman/pen/yLGMxyO?editors=1000

I would note, that using `document.querySelectorAll` will only work for any components in the initial document render (this is also potentially true for `DOMContentLoaded`, but I haven't verified that yet). If you want to handle any new elements added after the fact, you would either need to check if `increment` is already defined in the web-component (and skip the `pending` check if it is), or add a mutation observer to process any new nodes added to the document. Let me know if you would like a code sample for what either of those would look like.

**Comment by JRJurman** [comment]
@rouilj - let me know if any of those work, or if you think a more elegant solution would be worthwhile here. I have been thinking about [making the mount script its own custom element](https://github.com/Tram-One/tram-lite/issues/26) (which could afford us more configuration options, like delaying the execution until DOMContentLoaded!

**Comment by rouilj** [comment]
Thanks for your ideas.

Thanks for the followup. You have given me some methods to work with.
Web Components are new to me and I am just exploring.

In [this message](https://github.com/Tram-One/tram-lite/issues/29#issuecomment-1712879514) you said:
> you would either need to check if `increment` is already defined in the web-component (and skip the
> `pending` check if it is), or add a mutation observer to process any new nodes added to the document.

How would I check to see if increment is defined in the web component? Is the increment function scoped
to the web component and unavailable outside of the component? 

Thanks for the thoughts.


(As an aside I live in Waltham.)

**Comment by JRJurman** [comment]
> (As an aside I live in Waltham.)

Haha, now I'll have to eventually organize a Tram Meetup 😆 

> How would I check to see if increment is defined in the web component?

If `increment` is defined in its own script tag at the bottom of the document, it'll just be available everywhere (so you can check if `window.increment` is `undefined`). 

Codepen that checks if increment is undefined:
https://codepen.io/JRJurman/pen/wvRdeoj?editors=1000

> Is the increment function scoped
to the web component and unavailable outside of the component?

There are no scoped functions for web-component, at least, not with how you define them in Tram-Lite, although we could always make an interface for that!

**Comment by JRJurman** [comment]
Closing this issue, I think there's a couple of options since this issue was posted (plus this predates the v4 API). If there's still questions or something that is difficult to do in the new API, we can open a new issue that reflects the latest API.
