### ISSUE TITLE
Bug: Images that use a template variable make a bad request on first load.

### ISSUE THREAD

**Issue by Peter-Kang** [Tram-One/tram-lite#6]
## Summary
https://github.com/Peter-Kang/CryptoCoinCollection/blob/11753981bff19308631144dcc76a404ad24116cc/main.js#L29C17-L29C21
![image](https://github.com/Tram-One/tram-lite/assets/4218148/36c7718e-cd23-4561-826d-07f70a784245)

**Comment by JRJurman** [comment]
I made a codepen for this, but I'm not seeing any errors there - I'll have to try to run this locally, or come up with another locally failing example.

https://codepen.io/JRJurman/pen/oNQpeXd?editors=1111

**Comment by Peter-Kang** [comment]
It's a timing issue somewhere. It doesn't consistently appear, but we made it appear with break points that time

**Comment by JRJurman** [comment]
While the underlying code here hasn't changed that much, this was 2 major versions back.

I think we need a minimal code-sample (either in codepen, gist, or github repo), that shows this issue consistently.

For now, closing this, but if we do run into this again, happy to re-open!
