### ISSUE TITLE
Suggest: Minify tramlite

### ISSUE THREAD

**Issue by FJLendinez** [Tram-One/tram-lite#8]
## Summary
Tramlite is tiny enough to don't need the minification process but it appears to be bigger in tables like [unsuckjs](https://unsuckjs.com/).

Once minified, tramlite can weight only 4.3kb, less than a half of the original size.

Anyway, good job for the library, it has a lot of potential

**Comment by JRJurman** [comment]
Good call! I've been slightly hesitant on adding a ton of build tooling here, but given the margins here are so tight, and the fact that our consumers probably won't have build tooling to minify this, I agree that this totally makes sense to add. 

I have some rollup config from other projects that I can look at copying over to here (or maybe I'll extract that out into its own repo 😆)

**Comment by JRJurman** [comment]
This has been resolved in v2.5.1 - we now have a minified version available here: https://unpkg.com/tram-lite@2.5.1/src/tram-lite.min.js

The size (gzipped and minified) totals only 1.3 KB, so it's an insane amount of size we're saving here!

![screenshot of a network chart, in the name column, it says tram-lite.min.js, in the size column it says 1.3 kB, in the time column it says 17ms](https://github.com/Tram-One/tram-lite/assets/326557/f6cdd011-b87b-49f1-9ca8-ac3d89edd9d4)

Additionally, there is a PR out to update the advertised minified+gzipped size on unsuckjs.

Thanks again for bringing this up 👏
